version: "3.5"

networks:
  mariadb:
  mongo:

volumes:
  db-mariadb:
  db-mongo:
  user-uploads:

services:
  site:
    image: $REGISTRY/$PROJECT_NAME
    environment:
      RAILS_ENV: development
      MONGO_DATABASE: $MONGO_DEV_DATABASE
      MONGO_USER: $MONGO_USER
      MONGO_PASSWORD: $MONGO_PASSWORD
      MARIADB_DATABASE: $MARIADB_DEV_DATABASE
      MARIADB_USER: $MARIADB_USER
      MARIADB_PASSWORD: $MARIADB_PASSWORD
      INSIDE_DOCKER: 1
    networks:
      - mariadb
      - mongo
    ports:
      - 3000:3000
    volumes:
      - user-uploads:/site/public/uploads
      - .:/site
    depends_on:
      - db-mariadb
      - db-mongo

  db-mariadb:
    image: mariadb:5.5
    environment:
      MYSQL_ROOT_PASSWORD: $MARIADB_ROOT_PASSWORD
      MYSQL_DATABASE: $MARIADB_DEV_DATABASE
      MYSQL_USER: $MARIADB_USER
      MYSQL_PASSWORD: $MARIADB_PASSWORD
    volumes:
      - db-mariadb:/var/lib/mysql
    networks:
      - mariadb

  db-mongo:
    image: mongo:3.2
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_ROOT_PASSWORD
      MONGO_INITDB_DATABASE: $MONGO_DEV_DATABASE
      MONGO_INITDB_USER: $MONGO_USER
      MONGO_INITDB_PASSWORD: $MONGO_PASSWORD
    volumes:
      - db-mongo:/data/db
      - ./docker/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
    networks:
      - mongo
