version: "3.5"

networks:
  db:
  mongo:
  nginx:
  proxy:
    external: true

volumes:
  dbdata:
  mongo:
  user-uploads:
  docroot:

services:
  nginx:
    image: nginx:stable
    networks:
      - proxy
      - nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - docroot:/docroot
    depends_on:
      - app
    deploy:
      labels:
        - "traefik.port=80"
        - "traefik.docker.network=proxy"
        - "traefik.frontend.rule=Host:rademade-admin-demo.demo-rademade.com"

  app:
    image: $REGISTRY/$PROJECT_NAME
    environment:
      RAILS_ENV: production
      MONGO_HOST: $MONGO_HOST
      MONGO_USER: $MONGO_USER
      MONGO_DATABASE: $MONGO_DATABASE
      MYSQL_HOST: $MYSQL_HOST
      MYSQL_USER: $MYSQL_USER
      MYSQL_DATABASE: $MYSQL_DATABASE
    networks:
      - db
      - mongo
      - nginx
    volumes:
      - user-uploads:/site/public/uploads
      - docroot:/docroot
    depends_on:
      - db
      - mongo

  db:
    image: mariadb:5.5
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_USER
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_USER
      MYSQL_DATABASE: $MYSQL_DATABASE
    networks:
      - db

  mongo:
    image: mongo:3.2
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_USER
      MONGO_INITDB_USER: $MONGO_USER
      MONGO_INITDB_PASSWORD: $MONGO_USER
      MONGO_INITDB_DATABASE: $MONGO_DATABASE
    volumes:
      - mongo:/data/db
      - ./bin/init-mongo:/docker-entrypoint-initdb.d/init-mongo.sh
    networks:
      - mongo
