version: "3.5"

services:
  app:
    build:
      context: .
    command: sh bin/start-dev
    volumes:
      - ./:/app
    env_file:
      - .env
    environment:
      NODE_ENV: development
      RAILS_ENV: development
      RACK_ENV: development
    ports:
      - "3000:3000"
    depends_on:
      - db
      - mongo
    tty: true
    stdin_open: true

  db:
    image: mariadb:5
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_USER}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"

  mongo:
    image: mongo:3.6
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_USER}
      MONGO_INITDB_USER: ${MONGO_USER}
      MONGO_INITDB_PASSWORD: ${MONGO_USER}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    volumes:
      - mongo:/data/db
      - ./bin/init-mongo:/docker-entrypoint-initdb.d/init-mongo.sh

volumes:
  dbdata:
  mongo:
  uploads:
