version: "3.5"

networks:
  db:
  mongo:

volumes:
  dbdata:
  mongo:
  user-uploads:

services:
  site:
    image: $REGISTRY/$PROJECT_NAME
    environment:
      RAILS_ENV: production
      MONGO_USER: $MONGO_USER
      MONGO_DATABASE: $MONGO_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_DATABASE: $MYSQL_DATABASE
      INSIDE_DOCKER: 1
    networks:
      - db
      - mongo
    ports:
      - 3000:3000
    volumes:
      - user-uploads:/site/public/uploads
    depends_on:
      - db-mariadb
      - db-mongo

  db-mariadb:
    image: mariadb:5.5
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_USER
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_USER
      MYSQL_DATABASE: $MYSQL_DATABASE
    networks:
      - db

  db-mongo:
    image: mongo:3.2
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_USER
      MONGO_INITDB_USER: $MONGO_USER
      MONGO_INITDB_PASSWORD: $MONGO_USER
      MONGO_INITDB_DATABASE: $MONGO_DATABASE
    volumes:
      - mongo:/data/db
      - ./docker/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
    networks:
      - mongo
