default: &default
<% if ENV['DATABASE_URL'] %>
  url: <%= ENV['DATABASE_URL'] %>
<% else %>
  adapter: mysql2
  host: <%= ENV['MYSQL_HOST'] || 'localhost' %>
  port: <%= ENV['MYSQL_PORT'] || '3306' %>
  username: <%= ENV['MYSQL_USER'] || ENV['USER'] %>
  password: <%= ENV['MYSQL_PASSWORD'] || ENV['MYSQL_USER'] %>
  database: <%= ENV['MYSQL_DATABASE'] || Rails.application.class.parent_name.downcase %>
  encoding: utf8
  timeout: 5000
  pool: <%= ENV['DB_POOL'] || ENV['RAILS_MAX_THREADS'] || 5 %>
<% end %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
