default: &default
  url:  <%= ENV['DATABASE_URL'] || "mysql2://%s:%s@%s:%s/%s?encoding=utf8&timeout=5000&pool=%s" % [ENV['MYSQL_USER'] || ENV['USER'], ENV['MYSQL_PASSWORD'], ENV['MYSQL_HOST'] || 'localhost', ENV['MYSQL_PORT'] || '3306', ENV['MYSQL_DATABASE'] || Rails.application.class.parent_name.downcase, ENV['DB_POOL'] || ENV['RAILS_MAX_THREADS'] || 5] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default