development:
  adapter: mysql2
  database: rademade_admin_dev
  encoding: utf8
  collation: utf8_general_ci
  username: root
  password: root
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  database: rademade_admin_test
  encoding: utf8
  collation: utf8_general_ci
  username: root
  password: root
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  database: rademade_admin
  encoding: utf8
  collation: utf8_general_ci
  username: root
  password: root
  pool: 5
  timeout: 5000
