development:
  adapter: mysql2
<% if ENV['INSIDE_DOCKER'] %>
  host: db-mariadb
  username: <%= ENV['MARIADB_USER'] %>
  password: <%= ENV['MARIADB_PASSWORD'] %>
  database: <%= ENV['MARIADB_DATABASE'] %>
<% else %>
  username: root
  database: rademade_admin_demo_development
<% end %>

test:
  adapter: mysql2
  database: rademade_admin_test
  encoding: utf8
  collation: utf8_general_ci
  username: root
  password: root
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  host: db-mariadb
  username: <%= ENV['MARIADB_USER'] %>
  password: <%= ENV['MARIADB_PASSWORD'] %>
  database: <%= ENV['MARIADB_DATABASE'] %>
