development:
  clients:
    default:
<% if ENV['INSIDE_DOCKER'] %>
      database: <%= ENV['MONGO_DATABASE'] %>
      hosts:
        - db-mongo:27017
      options:
        user: <%= ENV['MONGO_USER'] %>
        password: <%= ENV['MONGO_PASSWORD'] %>
<% else %>
      database: rademade_admin_demo_development
      hosts:
        - localhost:27017
<% end %>
test:
  clients:
    default:
      database: rademade_admin_test
      hosts:
        - localhost:27017
production:
  clients:
    default:
      database: <%= ENV['MONGO_DATABASE'] %>
      hosts:
        - db-mongo:27017
      options:
        user: <%= ENV['MONGO_USER'] %>
        password: <%= ENV['MONGO_PASSWORD'] %>
