development:
  clients:
    default:
      database: rademade_admin_dev
      hosts:
        - localhost:27017
test:
  clients:
    default:
      database: rademade_admin_test
      hosts:
        - localhost:27017
production:
  clients:
    default:
      database: rademade_admin
      hosts:
        - localhost:27017