default: &default
  clients:
    default:
      database: <%= ENV['MONGO_DATABASE'] %>
      hosts:
        - "<%= ENV['MONGO_HOST'] %>:<%= ENV['MONGO_PORT'] %>"
      options:
        user: <%= ENV['MONGO_USER'] %>
        password: <%= ENV['MONGO_PASSWORD'] || ENV['MONGO_USER'] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
