development:
  clients:
    default:
      database: rademade_admin_dev
      hosts:
        - localhost:27017
test:
  clients:
    default:
      database: rademade_admin_test
      hosts:
        - localhost:27017
production:
  clients:
    default:
      database: <%= ENV['MONGO_DATABASE'] %>
      hosts:
        - db-mongo:27017
      options:
        user: <%= ENV['MONGO_USER'] %>
        password: <%= ENV['MONGO_PASSWORD'] %>
