# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 425681d824ab4b55c9fb5663cef16c535e9e34e73352db75f26114371d5dffd3f35b49bdb923ef0f50115ddb046dba33112fc4382cd68ed6757287142b692d5a

test:
  secret_key_base: ea7755e3dfdec87fd6356ec5b9bcd29e3749d9bbd460f1bebf698528a9d3101c7d60fa34ffa1ac25d82da5f14880b744164e7c01fb5e1013efab896ee0ea3cb9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
