default: &default
  adapter: mysql2
  host: <%= ENV['MYSQL_HOST'] %>
  user: <%= ENV['MYSQL_USER'] %>
  password: <%= ENV['MYSQL_PASSWORD'] || ENV['MYSQL_USER'] %>
  database: <%= ENV['MYSQL_DATABASE'] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
