development:
  adapter: mysql2
  host: localhost
  database: rademade_admin_dev
  user: root
  password: root

test:
  adapter: mysql2
  host: localhost
  database: rademade_admin_test
  user: root
  password: root

production:
  adapter: mysql2
  host: db-mariadb
  user: <%= ENV['MARIADB_USER'] %>
  password: <%= ENV['MARIADB_PASSWORD'] %>
  database: <%= ENV['MARIADB_DATABASE'] %>
